### ISSUE TITLE
JSON Decode error if no data yet in harvest

### ISSUE THREAD

**Issue by twistdmnd** [wilau2/harvest-balance-calculator#15]
# Prerequisites
Have a brand new account without any data logged

# Steps to reproduce
create config.json.secret file
Compile and run docker file

# Expected Behavior
Returns the actual number of hours in Harvest

# Current Behavior
docker run harvest-balance-calculator
total_should_of_worked_time
3075.0
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    user_id = harvest_http_client.get_me()["id"]
  File "/www/HarvestHttpClient/Client.py", line 25, in get_me
    return self.__get_single_result(route, self.headers)
  File "/www/HarvestHttpClient/Client.py", line 39, in __get_single_result
    response = json.loads(str_response)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wilau2** [comment]
TMYK: the get_me() call is necessary to allow admins to run this program for their own timesheet without getting all the information of everyone in the organization.
